version: "3.7"
services:
  database:
    image: mariadb:10
    ports:
      - "3306:3306"
    restart: "unless-stopped"
    environment:
      - TZ="Asia/Seoul"
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_ROOT_HOST=%
      - MARIADB_DATABASE=tododb
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    networks:
      - system
  api:
    image: todo-image
    ports:
      - "8080:8080"
    restart: "unless-stopped"
    depends_on:
      - database
    networks:
      - system
networks:
  system:
    driver: bridge
